MERGE INTO "sizingtest"."<INSERT_RUN_ID_HERE>".processed_table p
USING (
    SELECT DISTINCT
        "managedObjectId",
        "measuringNodeId",
        "time",
        "date",
        "hour",
        "C_H111" - 10000000.0 AS "D1",
        "C_H112" - 10000000.0 AS "D2",
        "C_H113" - 10000000.0 AS "D3",
        "C_H114" - 10000000.0 AS "D4",
        "C_H115" - 10000000.0 AS "D5",
        "C_H116" - 10000000.0 AS "D6",
        "C_H117" - 10000000.0 AS "D7",
        "C_H118" - 10000000.0 AS "D8",
        "C_H119" - 10000000.0 AS "D9",
        "C_H120" - 10000000.0 AS "D10",
        "C_H121" - 10000000.0 AS "D11",
        "C_H122" - 10000000.0 AS "D12",
        "C_H123" - 10000000.0 AS "D13",
        "C_H124" - 10000000.0 AS "D14",
        "C_H125" - 10000000.0 AS "D15",
        "C_H126" - 10000000.0 AS "D16",
        "C_H127" - 10000000.0 AS "D17",
        "C_H128" - 10000000.0 AS "D18",
        "C_H129" - 10000000.0 AS "D19",
        "C_H130" - 10000000.0 AS "D20",
        CAST(NULL AS DOUBLE) AS "D21",
        CAST(NULL AS DOUBLE) AS "D22",
        CAST(NULL AS DOUBLE) AS "D23",
        CAST(NULL AS DOUBLE) AS "D24",
        CAST(NULL AS DOUBLE) AS "D25",
        CAST(NULL AS DOUBLE) AS "D26",
        CAST(NULL AS DOUBLE) AS "D27",
        CAST(NULL AS DOUBLE) AS "D28",
        CAST(NULL AS DOUBLE) AS "D29",
        CAST(NULL AS DOUBLE) AS "D30",
        CAST(NULL AS DOUBLE) AS "D31",
        CAST(NULL AS DOUBLE) AS "D32",
        CAST(NULL AS DOUBLE) AS "D33",
        CAST(NULL AS DOUBLE) AS "D34",
        CAST(NULL AS DOUBLE) AS "D35",
        CAST(NULL AS DOUBLE) AS "D36",
        CAST(NULL AS DOUBLE) AS "D37",
        CAST(NULL AS DOUBLE) AS "D38",
        CAST(NULL AS DOUBLE) AS "D39",
        CAST(NULL AS DOUBLE) AS "D40",
        CAST(NULL AS DOUBLE) AS "D41",
        CAST(NULL AS DOUBLE) AS "D42",
        CAST(NULL AS DOUBLE) AS "D43",
        CAST(NULL AS DOUBLE) AS "D44",
        CAST(NULL AS DOUBLE) AS "D45",
        CAST(NULL AS DOUBLE) AS "D46",
        CAST(NULL AS DOUBLE) AS "D47",
        CAST(NULL AS DOUBLE) AS "D48",
        CAST(NULL AS DOUBLE) AS "D49",
        CAST(NULL AS DOUBLE) AS "D50",
        CAST(NULL AS DOUBLE) AS "D51",
        CAST(NULL AS DOUBLE) AS "D52",
        CAST(NULL AS DOUBLE) AS "D53",
        CAST(NULL AS DOUBLE) AS "D54",
        CAST(NULL AS DOUBLE) AS "D55",
        CAST(NULL AS DOUBLE) AS "D56",
        CAST(NULL AS DOUBLE) AS "D57",
        CAST(NULL AS DOUBLE) AS "D58",
        CAST(NULL AS DOUBLE) AS "D59",
        CAST(NULL AS DOUBLE) AS "D60",
        CAST(NULL AS DOUBLE) AS "D61",
        CAST(NULL AS DOUBLE) AS "D62",
        CAST(NULL AS DOUBLE) AS "D63",
        CAST(NULL AS DOUBLE) AS "D64",
        CAST(NULL AS DOUBLE) AS "D65",
        CAST(NULL AS DOUBLE) AS "D66",
        CAST(NULL AS DOUBLE) AS "D67",
        CAST(NULL AS DOUBLE) AS "D68",
        CAST(NULL AS DOUBLE) AS "D69",
        CAST(NULL AS DOUBLE) AS "D70",
        CAST(NULL AS DOUBLE) AS "D71",
        CAST(NULL AS DOUBLE) AS "D72",
        CAST(NULL AS DOUBLE) AS "D73",
        CAST(NULL AS DOUBLE) AS "D74",
        CAST(NULL AS DOUBLE) AS "D75",
        CAST(NULL AS DOUBLE) AS "D76",
        CAST(NULL AS DOUBLE) AS "D77",
        CAST(NULL AS DOUBLE) AS "D78",
        CAST(NULL AS DOUBLE) AS "D79",
        CAST(NULL AS DOUBLE) AS "D80",
        CAST(NULL AS DOUBLE) AS "D81",
        CAST(NULL AS DOUBLE) AS "D82",
        CAST(NULL AS DOUBLE) AS "D83",
        CAST(NULL AS DOUBLE) AS "D84",
        CAST(NULL AS DOUBLE) AS "D85",
        CAST(NULL AS DOUBLE) AS "D86",
        CAST(NULL AS DOUBLE) AS "D87",
        CAST(NULL AS DOUBLE) AS "D88",
        CAST(NULL AS DOUBLE) AS "D89",
        CAST(NULL AS DOUBLE) AS "D90",
        CAST(NULL AS DOUBLE) AS "D91",
        CAST(NULL AS DOUBLE) AS "D92",
        CAST(NULL AS DOUBLE) AS "D93",
        CAST(NULL AS DOUBLE) AS "D94",
        CAST(NULL AS DOUBLE) AS "D95",
        CAST(NULL AS DOUBLE) AS "D96",
        CAST(NULL AS DOUBLE) AS "D97",
        CAST(NULL AS DOUBLE) AS "D98",
        CAST(NULL AS DOUBLE) AS "D99",
        CAST(NULL AS DOUBLE) AS "D100",
        CAST(NULL AS DOUBLE) AS "D101",
        CAST(NULL AS DOUBLE) AS "D102",
        CAST(NULL AS DOUBLE) AS "D103",
        CAST(NULL AS DOUBLE) AS "D104",
        CAST(NULL AS DOUBLE) AS "D105",
        CAST(NULL AS DOUBLE) AS "D106",
        CAST(NULL AS DOUBLE) AS "D107",
        CAST(NULL AS DOUBLE) AS "D108",
        CAST(NULL AS DOUBLE) AS "D109",
        CAST(NULL AS DOUBLE) AS "D110",
        CAST(NULL AS DOUBLE) AS "D111",
        CAST(NULL AS DOUBLE) AS "D112",
        CAST(NULL AS DOUBLE) AS "D113",
        CAST(NULL AS DOUBLE) AS "D114",
        CAST(NULL AS DOUBLE) AS "D115",
        CAST(NULL AS DOUBLE) AS "D116",
        CAST(NULL AS DOUBLE) AS "D117",
        CAST(NULL AS DOUBLE) AS "D118",
        CAST(NULL AS DOUBLE) AS "D119",
        CAST(NULL AS DOUBLE) AS "D120",
        CAST(NULL AS DOUBLE) AS "D121",
        CAST(NULL AS DOUBLE) AS "D122",
        CAST(NULL AS DOUBLE) AS "D123",
        CAST(NULL AS DOUBLE) AS "D124",
        CAST(NULL AS DOUBLE) AS "D125",
        CAST(NULL AS DOUBLE) AS "D126",
        CAST(NULL AS DOUBLE) AS "D127",
        CAST(NULL AS DOUBLE) AS "D128",
        CAST(NULL AS DOUBLE) AS "D129",
        CAST(NULL AS DOUBLE) AS "D130",
        CAST(NULL AS DOUBLE) AS "D131",
        CAST(NULL AS DOUBLE) AS "D132",
        CAST(NULL AS DOUBLE) AS "D133",
        CAST(NULL AS DOUBLE) AS "D134",
        CAST(NULL AS DOUBLE) AS "D135",
        CAST(NULL AS DOUBLE) AS "D136",
        CAST(NULL AS DOUBLE) AS "D137",
        CAST(NULL AS DOUBLE) AS "D138",
        CAST(NULL AS DOUBLE) AS "D139",
        CAST(NULL AS DOUBLE) AS "D140",
        CAST(NULL AS DOUBLE) AS "D141",
        CAST(NULL AS DOUBLE) AS "D142",
        CAST(NULL AS DOUBLE) AS "D143",
        CAST(NULL AS DOUBLE) AS "D144",
        CAST(NULL AS DOUBLE) AS "D145",
        CAST(NULL AS DOUBLE) AS "D146",
        CAST(NULL AS DOUBLE) AS "D147",
        CAST(NULL AS DOUBLE) AS "D148",
        CAST(NULL AS DOUBLE) AS "D149",
        CAST(NULL AS DOUBLE) AS "D150",
        CAST(NULL AS DOUBLE) AS "D151",
        CAST(NULL AS DOUBLE) AS "D152",
        CAST(NULL AS DOUBLE) AS "D153",
        CAST(NULL AS DOUBLE) AS "D154",
        CAST(NULL AS DOUBLE) AS "D155",
        CAST(NULL AS DOUBLE) AS "D156",
        CAST(NULL AS DOUBLE) AS "D157",
        CAST(NULL AS DOUBLE) AS "D158",
        CAST(NULL AS DOUBLE) AS "D159",
        CAST(NULL AS DOUBLE) AS "D160",
        CAST(NULL AS DOUBLE) AS "D161",
        CAST(NULL AS DOUBLE) AS "D162",
        CAST(NULL AS DOUBLE) AS "D163",
        CAST(NULL AS DOUBLE) AS "D164",
        CAST(NULL AS DOUBLE) AS "D165",
        CAST(NULL AS DOUBLE) AS "D166",
        CAST(NULL AS DOUBLE) AS "D167",
        CAST(NULL AS DOUBLE) AS "D168",
        CAST(NULL AS DOUBLE) AS "D169",
        CAST(NULL AS DOUBLE) AS "D170",
        CAST(NULL AS DOUBLE) AS "D171",
        CAST(NULL AS DOUBLE) AS "D172",
        CAST(NULL AS DOUBLE) AS "D173",
        CAST(NULL AS DOUBLE) AS "D174",
        CAST(NULL AS DOUBLE) AS "D175",
        CAST(NULL AS DOUBLE) AS "D176",
        CAST(NULL AS DOUBLE) AS "D177",
        CAST(NULL AS DOUBLE) AS "D178",
        CAST(NULL AS DOUBLE) AS "D179",
        CAST(NULL AS DOUBLE) AS "D180",
        CAST(NULL AS DOUBLE) AS "D181",
        CAST(NULL AS DOUBLE) AS "D182",
        CAST(NULL AS DOUBLE) AS "D183",
        CAST(NULL AS DOUBLE) AS "D184",
        CAST(NULL AS DOUBLE) AS "D185",
        CAST(NULL AS DOUBLE) AS "D186",
        CAST(NULL AS DOUBLE) AS "D187",
        CAST(NULL AS DOUBLE) AS "D188",
        CAST(NULL AS DOUBLE) AS "D189",
        CAST(NULL AS DOUBLE) AS "D190",
        CAST(NULL AS DOUBLE) AS "D191",
        CAST(NULL AS DOUBLE) AS "D192",
        CAST(NULL AS DOUBLE) AS "D193",
        CAST(NULL AS DOUBLE) AS "D194",
        CAST(NULL AS DOUBLE) AS "D195",
        CAST(NULL AS DOUBLE) AS "D196",
        CAST(NULL AS DOUBLE) AS "D197",
        CAST(NULL AS DOUBLE) AS "D198",
        CAST(NULL AS DOUBLE) AS "D199",
        CAST(NULL AS DOUBLE) AS "D200",
        CAST(NULL AS DOUBLE) AS "D201",
        CAST(NULL AS DOUBLE) AS "D202",
        CAST(NULL AS DOUBLE) AS "D203",
        CAST(NULL AS DOUBLE) AS "D204",
        CAST(NULL AS DOUBLE) AS "D205",
        CAST(NULL AS DOUBLE) AS "D206",
        CAST(NULL AS DOUBLE) AS "D207",
        CAST(NULL AS DOUBLE) AS "D208",
        CAST(NULL AS DOUBLE) AS "D209",
        CAST(NULL AS DOUBLE) AS "D210",
        CAST(NULL AS DOUBLE) AS "D211",
        CAST(NULL AS DOUBLE) AS "D212",
        CAST(NULL AS DOUBLE) AS "D213",
        CAST(NULL AS DOUBLE) AS "D214",
        CAST(NULL AS DOUBLE) AS "D215",
        CAST(NULL AS DOUBLE) AS "D216",
        CAST(NULL AS DOUBLE) AS "D217",
        CAST(NULL AS DOUBLE) AS "D218",
        CAST(NULL AS DOUBLE) AS "D219",
        CAST(NULL AS DOUBLE) AS "D220",
        CAST(NULL AS DOUBLE) AS "D221",
        CAST(NULL AS DOUBLE) AS "D222",
        CAST(NULL AS DOUBLE) AS "D223",
        CAST(NULL AS DOUBLE) AS "D224",
        CAST(NULL AS DOUBLE) AS "D225",
        CAST(NULL AS DOUBLE) AS "D226",
        CAST(NULL AS DOUBLE) AS "D227",
        CAST(NULL AS DOUBLE) AS "D228",
        CAST(NULL AS DOUBLE) AS "D229",
        CAST(NULL AS DOUBLE) AS "D230",
        CAST(NULL AS DOUBLE) AS "D231",
        CAST(NULL AS DOUBLE) AS "D232",
        CAST(NULL AS DOUBLE) AS "D233",
        CAST(NULL AS DOUBLE) AS "D234",
        CAST(NULL AS DOUBLE) AS "D235",
        CAST(NULL AS DOUBLE) AS "D236",
        CAST(NULL AS DOUBLE) AS "D237",
        CAST(NULL AS DOUBLE) AS "D238",
        CAST(NULL AS DOUBLE) AS "D239",
        CAST(NULL AS DOUBLE) AS "D240",
        CAST(NULL AS DOUBLE) AS "D241",
        CAST(NULL AS DOUBLE) AS "D242",
        CAST(NULL AS DOUBLE) AS "D243",
        CAST(NULL AS DOUBLE) AS "D244",
        CAST(NULL AS DOUBLE) AS "D245",
        CAST(NULL AS DOUBLE) AS "D246",
        CAST(NULL AS DOUBLE) AS "D247",
        CAST(NULL AS DOUBLE) AS "D248",
        CAST(NULL AS DOUBLE) AS "D249",
        CAST(NULL AS DOUBLE) AS "D250",
        CAST(NULL AS DOUBLE) AS "D251",
        CAST(NULL AS DOUBLE) AS "D252",
        CAST(NULL AS DOUBLE) AS "D253",
        CAST(NULL AS DOUBLE) AS "D254",
        CAST(NULL AS DOUBLE) AS "D255",
        CAST(NULL AS DOUBLE) AS "D256",
        CAST(NULL AS DOUBLE) AS "D257",
        CAST(NULL AS DOUBLE) AS "D258",
        CAST(NULL AS DOUBLE) AS "D259",
        CAST(NULL AS DOUBLE) AS "D260",
        CAST(NULL AS DOUBLE) AS "D261",
        CAST(NULL AS DOUBLE) AS "D262",
        CAST(NULL AS DOUBLE) AS "D263",
        CAST(NULL AS DOUBLE) AS "D264",
        CAST(NULL AS DOUBLE) AS "D265",
        CAST(NULL AS DOUBLE) AS "D266",
        CAST(NULL AS DOUBLE) AS "D267",
        CAST(NULL AS DOUBLE) AS "D268",
        CAST(NULL AS DOUBLE) AS "D269",
        CAST(NULL AS DOUBLE) AS "D270",
        "C_H101" || ' (updated)' AS "V1",
        "C_H102" || ' (updated)' AS "V2",
        "C_H103" || ' (updated)' AS "V3",
        "C_H104" || ' (updated)' AS "V4",
        "C_H105" || ' (updated)' AS "V5",
        "C_H106" || ' (updated)' AS "V6",
        "C_H107" || ' (updated)' AS "V7",
        "C_H108" || ' (updated)' AS "V8",
        "C_H109" || ' (updated)' AS "V9",
        "C_H110" || ' (updated)' AS "V10",
        NULL AS "V11",
        NULL AS "V12",
        NULL AS "V13",
        NULL AS "V14",
        NULL AS "V15",
        NULL AS "V16",
        NULL AS "V17",
        NULL AS "V18",
        NULL AS "V19",
        NULL AS "V20",
        NULL AS "V21",
        NULL AS "V22",
        NULL AS "V23",
        NULL AS "V24",
        NULL AS "V25",
        NULL AS "V26",
        NULL AS "V27",
        NULL AS "V28",
        NULL AS "V29",
        NULL AS "V30",
        NULL AS "V31",
        NULL AS "V32",
        NULL AS "V33",
        NULL AS "V34",
        NULL AS "V35",
        NULL AS "V36",
        NULL AS "V37",
        NULL AS "V38",
        NULL AS "V39",
        NULL AS "V40",
        NULL AS "V41",
        NULL AS "V42",
        NULL AS "V43",
        NULL AS "V44",
        NULL AS "V45",
        NULL AS "V46",
        NULL AS "V47",
        NULL AS "V48",
        NULL AS "V49",
        NULL AS "V50",
        NULL AS "V51",
        NULL AS "V52",
        NULL AS "V53",
        NULL AS "V54",
        NULL AS "V55",
        NULL AS "V56",
        NULL AS "V57",
        NULL AS "V58",
        NULL AS "V59",
        NULL AS "V60",
        NULL AS "V61",
        NULL AS "V62",
        NULL AS "V63",
        NULL AS "V64",
        NULL AS "V65",
        NULL AS "V66",
        NULL AS "V67",
        NULL AS "V68",
        NULL AS "V69",
        NULL AS "V70",
        NULL AS "V71",
        NULL AS "V72",
        NULL AS "V73",
        NULL AS "V74",
        NULL AS "V75",
        NULL AS "V76",
        NULL AS "V77",
        NULL AS "V78",
        NULL AS "V79",
        NULL AS "V80"
    FROM "sizingtest"."<INSERT_RUN_ID_HERE>".raw_table
    WHERE managedObjectId = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxmo-A' AND 
        measuringNodeId = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxmn-A' AND 
        "date" = '<INSERT_DATE_HERE>' AND "hour" = <INSERT_HOUR_HERE>
) AS r
ON p."date" = r."date" AND p."hour" = r."hour" AND p."managedObjectId" = r."managedObjectId" AND p."measuringNodeId" = r."measuringNodeId" AND p."time" = r."time"
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *