OPTIMIZE TABLE <INSERT_SOURCE_PATH_HERE>."<INSERT_RUN_ID_HERE>".raw_table
FOR PARTITIONS "date" = '<INSERT_DATE_HERE>' AND <INSERT_HOUR_RANGE_HERE>
(MIN_FILE_SIZE_MB=256, MAX_FILE_SIZE_MB=1000, TARGET_FILE_SIZE_MB=512)