OPTIMIZE TABLE sizingtest."<INSERT_RUN_ID_HERE>".processed_table
FOR PARTITIONS "date" = '<INSERT_DATE_HERE>' AND "hour" = <INSERT_HOUR_HERE>
(MIN_FILE_SIZE_MB=256, MAX_FILE_SIZE_MB=1000, TARGET_FILE_SIZE_MB=512)